# Generated by Django 6.0.3 on 2026-04-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_job_created_at_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='match_reasons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
