# Generated by Django 6.0.3 on 2026-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_resume_match_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
