# Generated by Django 6.0.3 on 2026-07-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_resume_education_score_resume_experience_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
