# Generated by Django 6.0.3 on 2026-07-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resume_education_text_resume_experience_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='shortlisted',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
