# Generated by Django 6.0.3 on 2026-07-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resume_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='matched_skills_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill_match_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
